[package]
name = "zoon"
version = "0.1.0"
authors = ["Martin Kavík <martin@kavik.cz>"]
edition = "2018"

[dependencies]
<<<<<<< HEAD
wasm-bindgen = "0.2.70"
console_error_panic_hook = { version = "0.1.6", default-features = false }
blocks_macro = { path = "../blocks_macro" }
s_var_macro = { path = "../s_var_macro" }
update_macro = { path = "../update_macro" }
cache_macro = { path = "../cache_macro" }
cmp_macro = { path = "../cmp_macro" }
tracked_call_macro = { path = "../tracked_call_macro" }
# @TODO remove rand and getrandom?
uuid = { version = "0.8.2", features = ["v4", "wasm-bindgen"], default_features = false }

[dependencies.web-sys]
version = "0.3.48"
features = [
    "Document",
    "Element",
    "Event",
    "EventTarget",
    "Node",
    "NodeList",
    "Text",
    "Window",
]
default-features = false
=======
wasm-bindgen = { version = "0.2.74", default-features = false }
web-sys = { version = "0.3.51", default-features = false }
futures-signals = { version = "0.3.20", default-features = false }
dominator = { version = "0.5.16", default-features = false }
paste = { version = "1.0.5", default-features = false }

static_ref_macro = { path = "../static_ref_macro", optional = true }
once_cell = { version = "1.7.2", features = ["race", "alloc"], default-features = false, optional = true }

console_error_panic_hook = { version = "0.1.6", default-features = false, optional = true }
wee_alloc = { version = "0.4.5", default-features = false, optional = true }
# wasm-tracing-allocator = { version = "0.1.1", default-features = false, optional = true }
enclose = { version = "1.1.8", default-features = false, optional = true }

ufmt = { version = "0.1.0", features = ["std"], default-features = false, optional = true }
lexical = { git = "https://github.com/Alexhuszagh/rust-lexical", rev = "7010efd", features = ["std"], default-features = false, optional = true }

[features]
default = ["static_ref", "panic_hook", "small_alloc", "clone"]
static_ref = ["static_ref_macro", "once_cell"]
panic_hook = ["console_error_panic_hook"]
small_alloc = ["wee_alloc"]
fast_alloc = []
# tracing_alloc = ["wasm-tracing-allocator"]
clone = ["enclose"]
fmt = ["ufmt", "lexical"]
>>>>>>> a70fd9927f5b90424db36fda687d6c6344278925
